export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const REQUEST_TOKEN_PENDING = 'REQUEST_TOKEN_PENDING';
export const REQUEST_TOKEN_FULFILLED = 'REQUEST_TOKEN_FULFILLED';
export const REQUEST_TOKEN_REJECTED = 'REQUEST_TOKEN_REJECTED';