export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const ADD_TO_WATCHLIST_PENDING = 'ADD_TO_WATCHLIST_PENDING';
export const ADD_TO_WATCHLIST_FULFILLED = 'ADD_TO_WATCHLIST_FULFILLED';
export const ADD_TO_WATCHLIST_REJECTED = 'ADD_TO_WATCHLIST_REJECTED';