export const GET_WATCHLIST = 'GET_WATCHLIST';
export const GET_WATCHLIST_PENDING = 'GET_WATCHLIST_PENDING';
export const GET_WATCHLIST_FULFILLED = 'GET_WATCHLIST_FULFILLED';
export const GET_WATCHLIST_REJECTED = 'GET_WATCHLIST_REJECTED';