export const DELETE_MOVIE_RATING = 'DELETE_MOVIE_RATING';
export const DELETE_MOVIE_RATING_PENDING = 'DELETE_MOVIE_RATING_PENDING';
export const DELETE_MOVIE_RATING_FULFILLED = 'DELETE_MOVIE_RATING_FULFILLED';
export const DELETE_MOVIE_RATING_REJECTED = 'DELETE_MOVIE_RATING_REJECTED';