export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_PENDING = 'FETCH_MOVIE_DETAILS_PENDING';
export const FETCH_MOVIE_DETAILS_FULFILLED = 'FETCH_MOVIE_DETAILS_FULFILLED';
export const FETCH_MOVIE_DETAILS_REJECTED = 'FETCH_MOVIE_DETAILS_REJECTED';