export const FETCH_MOVIE_REVIEWS = 'FETCH_MOVIE_REVIEWS';
export const FETCH_MOVIE_REVIEWS_PENDING = 'FETCH_MOVIE_REVIEWS_PENDING';
export const FETCH_MOVIE_REVIEWS_FULFILLED = 'FETCH_MOVIE_REVIEWS_FULFILLED';
export const FETCH_MOVIE_REVIEWS_REJECTED = 'FETCH_MOVIE_REVIEWS_REJECTED';