export const POST_MOVIE_RATING = 'POST_MOVIE_RATING';
export const POST_MOVIE_RATING_PENDING = 'POST_MOVIE_RATING_PENDING';
export const POST_MOVIE_RATING_FULFILLED = 'POST_MOVIE_RATING_FULFILLED';
export const POST_MOVIE_RATING_REJECTED = 'POST_MOVIE_RATING_REJECTED';