export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING';
export const SEARCH_MOVIE_FULFILLED = 'SEARCH_MOVIE_FULFILLED';
export const SEARCH_MOVIE_REJECTED = 'SEARCH_MOVIE_REJECTED';