export const FETCH_TRENDING_MOVIES = 'FETCH_TRENDING_MOVIES';
export const FETCH_TRENDING_MOVIES_PENDING = 'FETCH_TRENDING_MOVIES_PENDING';
export const FETCH_TRENDING_MOVIES_FULFILLED = 'FETCH_TRENDING_MOVIES_FULFILLED';
export const FETCH_TRENDING_MOVIES_REJECTED = 'FETCH_TRENDING_MOVIES_REJECTED';