export const CREATE_SESSION_ID = 'CREATE_SESSION_ID';
export const CREATE_SESSION_ID_PENDING = 'CREATE_SESSION_ID_PENDING';
export const CREATE_SESSION_ID_FULFILLED = 'CREATE_SESSION_ID_FULFILLED';
export const CREATE_SESSION_ID_REJECTED = 'CREATE_SESSION_ID_REJECTED';